### ISSUE TITLE
[Milestone] v1

### ISSUE THREAD

**Issue by jcbhmr** [bindrs/rfd.js#2]
- [x] Implement the interfaces and stuff described in https://docs.rs/rfd/latest/rfd/
- [x] Add a basic JavaScript test for CI
- [x] Create a demo for manual testing
- [x] Get it to build for Windows
- [x] Get it to build for macOS
- [x] #1 
- [x] Release to npm
- [x] Publish docs website
- [x] ~~#3~~

**Comment by jcbhmr** [comment]
I'm waiting to see if there's a Rust-JS organization that I could put this under like:
https://github.com/rustyjs/project-template/issues/59
https://github.com/crates-js/reqwest/issues/1

**Comment by jcbhmr** [comment]
Doing one last ping! @devtomio @bbqsrc

**Comment by jcbhmr** [comment]
Ugh. I had to make my own org. 🤢
